apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongdb-pv
  labels:
    type: local
  labels:
    app: mongdb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mongdb"
