---
- name: Update repository list
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker.io
  ansible.builtin.apt:
    name: docker.io
    state: latest

- name: Start and enable Docker
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: docker

- name: Add Kubernetes Signing Key and Software Repositories
  shell: "{{item}}"
  with_items:
    - "sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://dl.k8s.io/apt/doc/apt-key.gpg"
    - 'echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list'

- name: Install kubeadm, kubelet, and kubectl
  ansible.builtin.apt:
    pkg:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: true

- name: Mark packages
  shell: sudo apt-mark hold kubeadm kubelet kubectl

- name: Disable Swap
  shell: "{{item}}"
  with_items:
    - "sudo swapoff -a"
    - 'sudo sed -i "/ swap / s/^\(.*\)$/#\1/g" /etc/fstab'

- name: Configure containerd.conf
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    regexp: "{{item.regex}}"
    line: "{{item.line}}"
    create: true
    owner: root
    group: root
  with_items:
    - {'regex':'^overlay$','line':'overlay'}
    - {'regex':'^br_netfilter$','line':'br_netfilter'}

- name: Configure kubernetes.conf
  lineinfile:
    path: /etc/sysctl.d/kubernetes.conf
    regexp: "{{item.regex}}"
    line: "{{item.line}}"
    create: true
    owner: root
    group: root
  with_items:
    - {'regex':'^net.bridge.bridge-nf-call-ip6tables =','line':'net.bridge.bridge-nf-call-ip6tables = 1'}
    - {'regex':'^net.bridge.bridge-nf-call-iptables =','line':'net.bridge.bridge-nf-call-iptables = 1'}
    - {'regex':'^net.ipv4.ip_forward =','line':'net.ipv4.ip_forward = 1'}

- name: Reload configuration
  shell: sudo sysctl --system