apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master-deployment
  labels:
    app: jenkis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
        - name: jenkins-master
          image: joshuad23/jenkins-master
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /var/lib/jenkins
      volumes:
        - name: jenkins-persistent-storage
          persistentVolumeClaim:
            claimName: jenkins-pvc
